mode     : selfcontained
framework: purus
github:
  user: snowdj
  repo: poirotBlog

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: snowdj



